[package]
name = "bws-rest-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitwarden = { version = "*", features = ["secrets"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
uuid = "1.4.1"
serde = "*"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0.75"
