name: Rust

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'Dockerfile'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
    - name: Fetch
      run: cargo fetch --verbose
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
