name: Rust

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'Dockerfile'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - name: Fetch
      run: cargo fetch --verbose
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
